sonar.projectKey=mitchins_wirestub
sonar.organization=mitchins

sonar.sources=Sources
sonar.tests=Tests
sonar.test.inclusions=Tests/**/*.swift
sonar.coverageReportPaths=coverage/sonar-coverage.xml
sonar.sourceEncoding=UTF-8
